baseURL: "https://divyansh7.netlify.app/"
languageCode: en-us
title: "Divyansh Tripathi | ML & Generative AI Specialist"
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: about
      name: About
      url: /about
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 40
    - identifier: experience
      name: Experience
      url: /experience
      weight: 50
    - identifier: tags
      name: Tags
      url: /tags
      weight: 60

params:
  # Theme settings
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # Enhanced SEO
  env: production

  # Home Page Enhancements
  profileMode:
    enabled: true
    title: "Divyansh Tripathi"
    subtitle: > 
      Welcome! I am an ML & Generative AI Specialist with expertise in developing scalable AI solutions.  
      I am currently pursuing **M.Tech in Data Science at IIT Roorkee** and ranked **AIR 75 in GATE (Data Science & AI)**.  
      Explore my work and let’s collaborate to build innovative solutions together!
    imageUrl: "home/dp2.jpg"
    imageWidth: 200
    imageHeight: 200
    buttons:
      - name: View Resume
        url: "https://drive.google.com/file/d/1GxXzisLcrsDfFcDeT93YUuRS5WsL-jvM/view?usp=sharing"
      - name: Explore Projects
        url: "/projects"
      - name: Contact Me
        url: "mailto:divyanshbro7@gmail.com"

  # List View
  hideDescriptionInList: false

  # Cover images for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # Social Icons
  socialIcons:
    - name: "email"
      url: "mailto:divyanshbro7@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/divyansh-tripathi-4bb66a205/"
    - name: "github"
      url: "https://github.com/divyansh-tripathi7"
    - name: "kaggle"
      url: "https://www.kaggle.com/divyanshtripathi7"
    - name: "leetcode"
      url: "https://leetcode.com/divyanshh007/"

  # Text search options
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

outputs:
  home:
    - HTML
    - RSS
    - JSON

# Allow HTML in Markdown
markup:
  goldmark:
    renderer:
      unsafe: true
